image:
  - Visual Studio 2017
configuration:
  - Release
artifacts:
  - name: executable
    path: SilentStreamBugFix\bin\$(configuration)\SilentStreamBugFix.exe
deploy:
  provider: GitHub
  draft: true
  artifact: executable
  description: 'Release 1.0.0'
  release: SilentStreamBugFix-v1.0.0
  auth_token:
    secure: dvOTTIWM4jQpigNFM+RpDRNvMee/t5gkG4j8LRL+EkxIStGulXZsr0tamQIPzb+t