image:
  - Visual Studio 2017
configuration:
  - Release
artifacts:
  - name: installer
    path: SilentStreamBugFix.Setup\bin\$(configuration)\SilentStreamBugFix.Setup.exe
deploy:
  provider: GitHub
  artifact: installer
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: 'Release $(APPVEYOR_REPO_TAG_NAME)'
  auth_token:
    secure: dvOTTIWM4jQpigNFM+RpDRNvMee/t5gkG4j8LRL+EkxIStGulXZsr0tamQIPzb+t
  on:
    APPVEYOR_REPO_TAG: true