image:
  - Visual Studio 2017
configuration:
  - Release
artifacts:
  - name: executable
    path: SilentStreamBugFix\bin\$(configuration)\SilentStreamBugFix.exe
deploy:
  provider: GitHub
  draft: true
  artifact: executable
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: 'Release $(APPVEYOR_REPO_TAG_NAME)'
  auth_token:
    secure: dvOTTIWM4jQpigNFM+RpDRNvMee/t5gkG4j8LRL+EkxIStGulXZsr0tamQIPzb+t
  on:
    APPVEYOR_REPO_TAG: true